version: "3.7"

services:
  sqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_db
    restart: always
    volumes:
      - ./mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: backend
    ports:
      - 3306:3306

  phpserve:
    image: phpmyadmin
    container_name: myphp
    ports:
      - 8888:80
    restart: always
    environment:
      - PMA_ARBITRARY=1

